# Quadro analítico histórico 

```{r, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE, 
  warning = FALSE, 
  eval = TRUE
)
```


## Disponibilidades Líquidas

Para responder as questões (a) e (b) sobre disponibilidades líquidas das UGs, elaboramos:

- Gráficos das séries temporais das disponibilidades líquidas de cada UG e Fonte de Recurso.
- Gráficos das séries temporais das disponibilidades líquidas consolidadas por UG.
- Indicadores de disponibilidades líquidas negativas para as UGs:
    - Proporção do tempo do período analisado com disponibilidade negativa.
    - Duração da disponibilidade negativa atual.

### Gráficos de séries temporais


### Indicadores por UG

1) Proporção do tempo do período analisado com disponibilidade negativa.


2) Duração da disponibilidade negativa atual.


## Classificações Orçamentárias e Financeiras

(c) Despesas e Vinculações


## Disponibilidades Líquidas por Vinculação

(d) revisitamos...


## Comportamento do Caixa por Movimentação

- Gráficos das séries temporais dos saldos e obrigações de cada UG e Fonte de Recurso.
- Gráficos das séries temporais dos saldos e obrigações consolidados por UG.
- Gráfico dos tempos entre duas movimentações de grande porte por UG e por Órgão.