--- 
title: "Empoçamento Orçamentário - Análise de Perfil das Disponibilidades Líquidas das Unidades Gestoras do Ministério da Justiça."
author: "R6 Estatística e Treinamentos LTDA"
date: "`r format(Sys.Date(), 'São Paulo, Brasil, %B de %Y')`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    lib_dir: "book_assets"
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: curso-r/stn-caixa
description: "STN-Caixa"
header-includes:
  - \AtBeginDocument{\renewcommand{\chaptername}{Capítulo}}
---


# Introdução

No contexto de finanças, segundo [@inst-fisc-indep], empoçamento é a diferença positiva entre o limite de pagamento e a despesa efetivamente paga em determinado período. O limite de pagamento corresponde ao fluxo mensal de liberação financeira por parte da Secretaria do Tesouro Nacional (STN) para órgãos que executam as despesas orçamentárias. Em outros termos, empoçamento é o fenômeno de recursos financeiros sem circulação por longo período de tempo e significa potencial ineficiência do uso de recursos públicos. 

Apesar de o empoçamento poder ser causado por projeções conservadoras de despesas obrigatórias, existe ainda empoçamentos decorrentes de despesas discricionárias (aquelas que não são obrigatórias em lei) e medidas imediatas ou de médio prazo podem ser tomadas para remediar esse problema.

O desafio está em encontrar as oportunidades de ações para redução de empoçamentos nas despesas discrionárias, porém, os dados do SIAFI permitem análises restrospectivas dos fluxos de caixa de cada órgão para cada fonte de recurso, permitindo, assim, explorar possíveis padrões de empoçamento. Uma vez que se tenha construído indicadores de empoçamento com base nos fluxos de caixa de cada órgão, órgãos competentes podem consumí-los e priorizar ações cabíveis.



## Objetivos

Os objetivos deste projeto são:

1) Analisar o comportamento do caixa e das obrigações financeiras dos órgãos federais, com a finalidade de fornecer informações para a gestão da programação financeira por parte do Tesouro Nacional, especificamente na detecção e priorização de ações à administração do fenômeno de empoçamento financeiro.

2) Propor metodologia e disponibilizar ferramentas abertas para replicá-la a qualquer órgão máximo brasileiro e internacional.


## Questões investigadass

De início, analisamos o perfil das despesas e receitas das unidades do Governo Federal, começando com os órgãos do Ministério da Justiça (que já possui um sistema de acompanhamento de despesas bem estruturado).

A análise procurou compatibilizar as informações orçamentárias com as informações financeiras. Chamamos de _classificadores orçamentários_: Função, Subfunção, Programa, Ação, Grupo de Despesa, Modalidade de Aplicação, Elemento de Despesa, Indicador de Resultado EOF, Indicador de Exceção Decreto. Como _classificadores financeiros_, nos referimos, essencialmente, à Vinculação de Pagamento.

A _Fonte de Recurso_ é um classificador comum a esses dois contextos, orçamentário e financeiro.

Com esse escopo em mente, em parceria com a equipe do GT-CEAD, as seguintes questões foram abordadas neste projeto:

a. Qual o comportamento do caixa e das obrigações a pagar (e da disponibilidade líquida) no período analisado^[Por órgão, por unidade e por fonte de recursos.]? 

b. Existem casos em que unidades de um mesmo órgão permanecem com disponibilidade líquida negativa, enquanto outras unidades desse mesmo órgão encontram-se com disponibilidade positiva? E se considerar a fonte de recursos, há casos em que o órgão passa por períodos com disponibilidade negativa em uma fonte enquanto há recursos disponíveis em outra fonte? E se considerar as duas situações conjuntamente^[Ou seja, uma unidade de um mesmo órgão fica com disponibilidade negativa em uma fonte, enquanto outra unidade desse mesmo órgão possui disponibilidade positiva nessa mesma fonte.]? 

c. Qual o comportamento do caixa das unidades em termos de movimentações?

d. Qual o intervalo entre duas operações^[Uma despesa alta seguida de um recebimento de recursos também alto.] de grande porte?

Para responder essas perguntas, utilizamos ferramentas descritivas e de modelagem preditiva, descritas nos Capítulos 3 e 4, respectivamente. 

## As bases de dados

Para responder as questões levantadas no item anterior, os dados do SIAFI foram divididos em três bases de dados:

- 1. base de movimentações diárias do limite de saque;
- 2. base de pagamentos diários;
- 3. base de movimentações diárias nas obrigações a pagar.

Com as Tabelas 1 e 3, calculamos a _disponibilidade líquida diária_ a partir da subtração entre os saldos diários do caixa (Tabela 1) e as obrigações a pagar (Tabela 3), para cada unidade gestora ou órgão, e para cada fonte de recursos.

Com as Tabelas 1 e 2, relacionamos no contexto dos pagamentos, as informações orçamentrárias (Tabela 2) com os vínculos de pagamento (Tabela 1).

Finalmente com a Tabela 1, analisamos as movimentações para tipo de documento, obtendo um histórico das movimentações de cada órgão e cada Unidade Gestora.

Na primeira etapa do projeto, essas bases foram estudadas e validadas. Bases auxiliares também foram construídas para facilitar as análises subsequentes. A documentação dessa etapa se encontra no Capítulo 2.

## Aplicativo e Ferramentas

Dada a riqueza de informações e granularidade das bases de dados, todos os resultados descritivos foram construídos em uma aplicação online, que permite a manipulação das visualizações a partir de filtros e seletores.

O aplicativo pode ser acessado a partir do seguinte link: 

[https://rseis.shinyapps.io/explorador_disponibilidades_liquidas_v3/]()

O código-fonte e manutenção do aplicativo foram repassados à equipe do GT-CEAD ao fim do projeto e estão acessíveis ao público no link:

[https://curso-r.github.io/empocamento/]()

O software necessário para utilizar as ferramentas é o [@r-core., Um resumo dos principais resultados se encontra no Capítulo 3.

## Análise preditiva

Os modelos utilizados neste projeto consideraram o algorítmo XGBoost [@xgboost], método de aprendizagem de máquina estado da arte dentro do contexto de modelagem preditiva. A descrição dos modelos ajustados e seus resultados se encontram no Capítulo 5.

## Oficina de repasses e implementação dos produtos

A última etapa do projeto consistiu de uma oficina de repasses, realizada presencialmente no GT-CEAD, no Tesouro Nacional, em Brasília. Nessa oficina, foi discutida a teoria por trás dos métodos aplicados, tal como apresentada neste relatório. Também foram apresentados e explicados os scripts em linguagem de programação R utilizados para implementar os modelos.

